### PR TITLE
Added missing ota states, prepared ota for new command

### PR DESCRIPTION
**Pull request by MartijnCharged**
All untested :wink:

### CODE REVIEW

**Comment by PimDoos** [comment]
Will test once 1.5.1 is released publicly

**Comment by berendhaan** [comment]
Go Go Go 🚀

**Comment by PimDoos** [comment]
Will test tonight :)

**Comment by PimDoos** [comment]
Looks like this doesn't work yet.
The SessyUpdate entity has two parts: 
- Get the version numbers for current and newest firmware from /api/v1/ota/status. Use the data in the key provided in update_target. If current < newest: Update available.
- Post to /api/v1/ota/start with the respective update_target to start updating

/api/v1/ota/status only returns keys self and serial, but not 'all'. The update entity would not know what is the current 'unified' version and as such cannot determine whether there are updates available or not.
```json
{
	"status":	"ok",
	"self":	{
		"installed_firmware":	{
			"version":	"1.5.1"
		},
		"available_firmware":	{
			"version":	"1.5.1"
		},
		"state":	"OTA_UP_TO_DATE",
		"update_progress":	0
	},
	"serial":	{
		"installed_firmware":	{
			"version":	"1.5.1"
		},
		"available_firmware":	{
			"version":	"1.5.1"
		},
		"state":	"OTA_UP_TO_DATE",
		"update_progress":	0
	}
}
```

@MartijnCharged I can refactor the SessyUpdate class to take an optional value 'version_source', so the entity uses one of the fields as reference for the currently installed version and latest available version. My preference would be to use the 'self' key as reference, since that one is always present. Do you see any potential problems with this?
Another approach would be to monitor the version numbers on both the 'self' and 'serial' targets. This method will take a bit more work and needs additional logic when updating the entity.
Both scenarios assume the 'serial' device always needs to have the same software version number as the 'self' device.

I'm also thinking about dropping the separate update entities alltogether and treat the SessyBattery devices as a single unit. So only a single update entity 'Sessy-XXXX Firmware' which updates both the Battery and the Dongle. The above would then still need to be rectified.

**Pull request merged**
